spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medec
    username: Medec
    password: Root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081